### ISSUE TITLE
Move compiler/jobs into this repo

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#12]
We have a repo [`compiler`](https://github.com/compilerla/compiler) with a [`jobs` folder](https://github.com/compilerla/compiler/tree/main/jobs) containing markdown files describing different job postings we've had. We'll likely be adding at least one new description there soon.

We link to these description files (directly to GitHub) in various forums: on our GitHub profile, Twitter, job boards, etc. and may also have openings to post soon.

Let's move that whole folder into this repository, so the descriptions become simple pages on our website that we can link to, like: `compiler.la/jobs/product-manager`.

*Note we'll want to replace `_` with `-` in the file name to make cleaner URLs*

## Todo

* [ ] Make the Compiler logo a link to the homepage
* [ ] Convert jobs to a [Jekyll collection](https://jekyllrb.com/docs/collections/), render each as a page (`output: true`)
* [ ] Create a jobs/index.html page with list of links for each job posting, add headings for `Accepting applications`, `Past opportunities`
* [ ] Add frontmatter to job posts for `open: true/false`, on jobs index, render under the separate headings
* [ ] On each job post, add back link to jobs index
* [ ] Ensure `careers@compiler.la` is a mailto link on each job post
