### ISSUE TITLE
Add ClickUp to /jobs

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#23]
ClickUp can link lists, tasks, and subtasks with web forms created in ClickUp.

## To-Dos
- [ ] Look into ClickUp API information: https://clickup.com/api
- [ ] Connect Netlify with ClickUp either through API or Zapier
- [ ] Add form submissions to [Inbox Careers@](https://app.clickup.com/8631512/v/li/59076007)
- [ ] Create a Custom field in ClickUp for `job-roles` and a dropdown option in Netlify for the applicant to fill out their role (product, delivery, UX/UI, software engineer, etc.)

**Comment by AnthonyRollins** [comment]
Job applications are submitted through ClickUp through the apply now button on the [jobs page](https://compiler.la/jobs).
