### ISSUE TITLE
Update styling on Job postings 

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#24]
## To-Do

- [x] Meeting with @segacy1 to introduce her to the website project

## Segacy To-Do
- [x] Build out new design for job listing page
- [x] Build out new design for job posting page

**Comment by segacy1** [comment]
Hello! To make the jobs page accessible on the site, we'll likely want to update our nav. 

We could:

- keep the nav mostly intact and add a hamburger menu for now (pic attached to illustrate the idea/not a final design)
- design a new nav to include jobs, capabilities statement, and could be scalable for future pages (if we think we'd have them)
- if jobs is the only new page, we could redesign the footer and add that as a link (esp if we don't expect that page to be high traffic for those coming to the site directly vs. coming from another channel (linkedin/github/glassdoor/twitter)

Anthony mentioned that we might want to keep our capabilities statement visible. I'll mock up an alternative version so we can discuss. 

@thekaveman @angela-tran @angela-tran Do we have plans to build any other pages in the immediate (ish) future? 

Please let me know what you all think!
<img width="1440" alt="Screen Shot 2022-10-27 at 7 53 28 PM" src="https://user-images.githubusercontent.com/33331853/198421284-4fa69486-fcf6-4c44-baa3-d7c168658d4a.png">

**Comment by AnthonyRollins** [comment]
@segacy1 I love the idea of a design that brings in navigation and sets us up for the future. We don't necessarily need the capabilities statement as the main thing, but I think it should be prioritized over the `Get in Touch` button.

**Comment by thekaveman** [comment]
I just have to say, I am absolutely in love with that menu pull-down, the bottom border!!! Soooooooo good 😍

**Comment by AnthonyRollins** [comment]
The next steps here are based on our call (01/13/23) regarding designs [Segacy's designs](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=586%3A413&t=6A3fbjiEY11ydJS2-0):

- [ ] @segacy1 to update the job posting page
- [ ] @segacy1 to clean up the job listing page
- [ ] @angela-tran @thekaveman to implement the new job posting styling
- [ ]  @angela-tran @thekaveman to implement the new job listing styling

As for the timeline, does the end of January or before the workshop in February work @segacy1 @angela-tran @thekaveman? Please let me know what you think here.

**Comment by segacy1** [comment]
@AnthonyRollins thank you for updating! I'm going to finish the intermediate jobs page now and will share it here by EOD.

**Comment by angela-tran** [comment]
> As for the timeline, does the end of January or before the workshop in February work @segacy1 @angela-tran @thekaveman? 

This timeline sounds fine 👍

**Comment by segacy1** [comment]
@thekaveman @AnthonyRollins @angela-tran would we still want the jobs page to be unlisted for the time being or do we want to include the new nav and hamburger menu? I've added the mocks for all [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=677%3A1890)

**Comment by angela-tran** [comment]
I think we initially didn't list the jobs page because it was all very MVP. With these polishes to move things around and have better spacing/styling, I can't think of a reason not to include the new nav and hamburger menu!

**Comment by segacy1** [comment]
@angela-tran since the styles and their names in Figma will be a bit of a WIP until after the workshop, would it work for you to use Figma's inspect for these mocks and I can clarify anything that might seem off?

**Comment by angela-tran** [comment]
@segacy1 Yep, that works for me. Thanks for noting that!

**Comment by AnthonyRollins** [comment]
@angela-tran I know you have been working on this lately, curious when you would expect the PR for these styling updates.

**Comment by angela-tran** [comment]
@AnthonyRollins Very timely question! @thekaveman and I were just talking about this earlier.

#36 is a pre-requisite for the styling updates for this ticket, and I've started/made headway on it. I am hoping to make more progress on it this week and from there move on to making this ticket's styling updates (which should be easier to make as a result of #36).

It's possible though that this will still be a work-in-progress when we meet next week for the website workshop.

**Comment by AnthonyRollins** [comment]
@angela-tran Thanks! I wanted to ensure we were still planning to implement those style changes and it looks like we are 👍

**Comment by AnthonyRollins** [comment]
@angela-tran @thekaveman, Would it be helpful for me to create a separate issue to implement the new styling to the job post and list pages? Here's the updated [designs](figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=677-1890&t=yWGVmWiKAu2G6aBd-0) on spacing.

**Comment by segacy1** [comment]
@o-ram yep, we can close and I've updated in figma with the new styling from our about/home pages!

**Comment by AnthonyRollins** [comment]
Ok, I am closing this issue and creating a new issue for the dev team to update the styling based on Figma designs. See #82
