### ISSUE TITLE
Brand work for website

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#33]
## To-Dos
- [x] Create Figma components for existing website designs.
- [x] Update styling (font size, colors, spacing) for all webpages
- [ ] Produce mobile mockups of pre-existing pages.

**Comment by segacy1** [comment]
Hi @AnthonyRollins! Do we have brand guidelines at the moment? I was poking around in drive and came across [this](https://drive.google.com/drive/folders/1_tXVp94IS5UKMIP8pHJOmarmaYCqrCWx?usp=sharing), but not sure if these docs are current. Want to make sure I'm using our styles as intended/document essentials in figma

**Comment by AnthonyRollins** [comment]
@segacy1 Yes, that is the right folder. I've been using this [style guide](https://drive.google.com/drive/folders/1GkzWwdCzbdpXKnxAeBya6tWYJWPFEZ5i), as its the most up-to-date.

**Comment by segacy1** [comment]
@AnthonyRollins @thekaveman @angela-tran hey folks! I’m making some progress on the UI library and I wanted to get some feedback on a couple of things before I kept going. The section I'd like feedback on is labeled "Dark Mode Update" [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=313%3A7116).

There are a few additions that we don't currently use on the live site, but I could foresee them being good to have as we build out the site further. Keep in mind, everything’s still a WIP!


**Color Naming Conventions**

_What I did:_ 
I segmented our color system into a few sections: Actions, Background, Text, and Brand. For dev, I assumed that it was easier for colors to be named by function. For design, I think having colors labeled by name is easier as we might create things that aren’t necessarily tied to function. That is what the brand section is for.

_Question:_
Does this work for you all? Anything that could be improved for you here?

**Light Mode vs. Dark Mode**

_Questions:_
- The current styling is all on a black background. Would we want to use only black backgrounds moving forward? Do we want an option for light mode/backgrounds? 
- The color palette that was designed for compiler was designed for a white background. I updated the two secondary colors (purple and indigo) to work better on a black background. Please let me know if that doesn't feel right - I can keep finessing the hues if so.

**Buttons + Component Anatomy**

_What I did:_ 
- To keep our buttons scalable for screen sizes and new designs, I created 3 sizes: large, normal, and small. 
- I added additional states for our two button types (primary/secondary). 

 _Questions:_
- What do you think about the button info (anatomy/specs) provided and how it’s laid out? Is there any information that you think is missing or unnecessary? Is there another format that would be more intuitive? If this works, I'll use this format for future components
- What do you think about having font style specifically for buttons (ex: font is called _button-small_)? 

As a freelancer, whenever I've been dropped into someone else's design system I always appreciate the additional context in figma. Trying to include all the things I wish I had when I've been in those situations!

Thank you!

**Comment by AnthonyRollins** [comment]
**Color Naming Conventions**
- I think this looks great, and it will be a lot easier for us to have names for colors, so we don't anyone confused. 

**Light Mode vs. Dark Mode**

- **Styling in Light Mode** I always like the dark background of our branding because it makes all of our bright colors (purple, teal, and green) pop, but I do think there might be a time we would need a white background, so I think we should include styling for a light background.
- **The color palette** I agree that those colors look better on dark backgrounds. I didn't know that our branding was built for a white background. 

**Buttons + Component Anatomy**

- I think this all makes sense to me, but I am curious about your thoughts on how the buttons are styled on `Hover` and `pressed`. Should we continue to use the styling work we have done there, or do you recommend a different design for when users `press` or `click` on the buttons.

**Comment by segacy1** [comment]
@AnthonyRollins since we made this before the workshop and all existing pages will change, should we close this ticket and note that mobile mocks will be included for all pages moving forward? 

Styling will also be finalized when Home and About pages are approved, so we can roll that into Q2 as well.

cc: @o-ram

**Comment by o-ram** [comment]
Based on @segacy1's comment above, I am closing this ticket. Mobile mocks will be included for all pages moving forward.

@segacy1 let me know if you'd like any new issues to be opened related to stylings!
