### ISSUE TITLE
Add Compiler Benefits & Perks content

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#39]
Update the Jobs list page to include information on [ Compiler's Benefits & Perks.](https://docs.google.com/document/d/1Zm0zxPQuS7x4XqUqGUoEtU8uzgxX-xC56dxs2u7fYEk/edit#heading=h.9wnq30ebdbke)

## To-Dos

- [ ] Design jobs listing page to include Compiler info along with a list of Job openings / Past openings
- [ ] Approve designs 
- [ ] Write content using benefits & perks doc
- [ ] Add to roadmap schedule for future page updates
- [ ] Develop using approve content and design
