### ISSUE TITLE
Prep/Develop website workshop  

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#40]
To build a roadmap and meet our OKR (develop website roadmap by Q1), Segacy will lead a workshop with the website team and others to understand the website's needs in 2023.

## To-Dos

- [x] @segacy1 to develop an outline for the workshop
- [x] @segacy1 host workshop in February
- [x] @AnthonyRollins @o-ram schedule website workshop
- [ ] #41

**Comment by AnthonyRollins** [comment]
The workshop has been completed, and now Olivia and I need to complete #41
