### ISSUE TITLE
Build out the 2023 website roadmap

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#41]
## To-Dos

- [x] Attend workshop to determine 2023 goals
- [x] #47
- [x] Create milestones/issues for 2023 based on the roadmap.
- [x] Discuss the timing of remaining pull requests for current jobs page revamp with the dev team

**Comment by o-ram** [comment]
Plan is in place for updating job styles for job lists and posts. Will be handled in other tickets.
