### ISSUE TITLE
Draft content for the Work page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#62]
## To-Dos
- [x] Finalize copy for the [work page](https://docs.google.com/document/d/1MVg0KN4Lkq3AiiTmotIC0dH_m-fRwItsLfJiok2N-B4/edit)
- [x] Finalize case studies for SCAG, ODS, CS strategy, and Data + Donuts
- [x] Finalize [designs](https://www.figma.com/proto/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?page-id=2794%3A937&type=design&node-id=2794-1269&viewport=291%2C-52%2C0.14&t=spDaRzZoFKTApykQ-1&scaling=min-zoom&mode=design)

**Comment by AnthonyRollins** [comment]
@ o-ram I believe we will have to take on content for the final piece of the website; this is not something I know we were too keen on doing, but this is the best foot forward. I will start drafting using Segacy's document and then move on to finishing up the case studies.

**Comment by o-ram** [comment]
Next steps to finalize copy:

- [ ] Turn notes from Kegan into one or two sentences for SCAG project
- [ ] Tag Marissa to review scheduling project
- [ ] Tag Scott to review ODS project
- [ ] Ask Laney to review the whole thing w/ fresh eyes

**Comment by o-ram** [comment]
Copy update:

Complete ✅ 
- Marissa has reviewed/approved the scheduler project
- Scott confirmed seeing the tag and will review ODS
- Laney has agreed to review the whole thing when we are ready for her to do so
- Kegan has been tagged in the email/testimonial script for SCAG (tracked in #152)

Next steps:

- [ ] Finalize tags
- [ ] Add accessible image descriptions for projects where we will have an image
- [ ] Add in the SCAG testimonial (dependent on approval)
- [ ] Receive sign off from Scott and Kegan for their respective projects
- [ ] Share doc with Laney

**Comment by AnthonyRollins** [comment]
@o-ram Did you want to assign some of the next steps to me?

**Comment by o-ram** [comment]
@AnthonyRollins it would be helpful if you could take a look at the Services section - I chopped them way down as we discussed, but it could use another pair of eyes. Feel free to edit them directly as you see fit. Otherwise, I believe the only 2 items left before I can send it to Laney are to get signoffs from Kegan and Scott on their respective projects. I just tagged Kegan again today and responded to a comment Scott left.

Would also be helpful if you could check with Andy to see if he can transfer the copy into Figma once we're ready since we can't.

**Comment by AnthonyRollins** [comment]
I talked with Sarah about transferring the content for the work page, so we should be good there once it has been finalized. I also went through the doc and made a few changes here and there.

**Comment by o-ram** [comment]
Content is finalized and has been handed off to design to insert it within the Figma files.
