### ISSUE TITLE
Development work for Work page

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#67]
## Tasks

- [ ] #205

After that first task is done, these tasks can be worked on by anyone in any order. Just make sure to stay in your section.

   - [x] #206
   - [x] #211
   - [x] #212
   - [x] #213
   - [x] #214
   - [x] #215
   - [x] #225
   - [ ] #231

**Comment by o-ram** [comment]
@thekaveman @angela-tran Designs and copy for the `Work page` are finalized within [this Figma file](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=3060%3A464&mode=design&t=BnDURqIpVpuu2lne-1). These are the same designs we reviewed with Segacy on 1/8. Sarah kindly inserted the final copy and cleaned it up for us, along with addressing comments from Machiko. Let us know if you have any questions or need anything else. Thanks! cc @AnthonyRollins

**Comment by angela-tran** [comment]
Here's what I'm thinking for breaking up the development work:

This first task is
   - [ ] Add new `/our-work` page with empty sections with background colors

All tasks below are blocked until the first task is done. Once unblocked, they can be worked on by anyone in any order. Just make sure to stay in your section.
   - [ ] Implement top "Our Work" section
      - should be similar to other pages' top sections
   - [ ] Implement "What We Do" section
      - add [accordion](https://getbootstrap.com/docs/5.0/components/accordion/) and the styles for it specified in Figma
      - add signpost icon
   - [ ] Implement "What We've Done" section
      - implement cards
         - tags on cards
         - non-image card
         - image card
      - card contents are driven by a data file?
      - "See more projects" button and "See fewer projects" button -> reference team member section from `/about` for how this is done
   - [ ] Add testimonial section
      - should be able to reference testimonial section from `/about`
   - [ ] Add "Ready to work together?" section
   - [ ] Add menu item for `/our-work` page named "Our Work"

**Comment by angela-tran** [comment]
I'll wait for #204 to be merged in before creating the rest of the tasks, so we can test out the workflow. (And so I don't have to manually set the project 😄)
